
development:
  adapter: postgresql
  encoding: unicode
  database: writeup_app_development
  pool: 5
  timeout: 5000
  username:  john
  password: password
  host: localhost
  port: 5433

test:
  adapter: postgresql
  database: writeup_app_test
  pool: 5
  timeout: 5000
  username:  john
  password:  password
  host: localhost
  port: 5433


production:
  adapter: postgresql
  database: writeup_app_production
  pool: 5
  timeout: 5000
  username:  john
  password:  